### PR TITLE
make athena a managed app

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/roadmap/issues/1097

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by anvddriesch** [comment]
Oh right. :smile: I forgot the icon.

**Comment by anvddriesch** [comment]
It's cute and I like it a lot!

**Comment by marians** [comment]
I'll provide the icon URL in a bit

**Comment by marians** [comment]
Here is the icon URL: https://s.giantswarm.io/app-icons/athena/1/light.svg

**Review by marians — APPROVED** [review]

**Comment by anvddriesch** [comment]
Oh wow we did the same commit :D sorry about that.

**Review by marians — APPROVED** [review]

**Pull request merged**
